import './globals.css'
import '../styles/index.scss'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import StyledComponentsRegistry from '../../lib/AntdRegistry'
import Link from 'next/link'
import { Layout, Menu } from 'antd'
import { MainHeader } from '@/components/level2/Header'

const inter = Inter({ subsets: ['latin'] })
const { Header, Content, Footer } = Layout
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StyledComponentsRegistry>
          <MainHeader />
          <main className="flex container mx-auto p-4" style={{ minHeight: 'calc(100vh - 46px)' }}>
            {children}
          </main>
        </StyledComponentsRegistry>
      </body>
    </html>
  )
}
