name: Run cypress testing
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build project
        uses: cypress-io/github-action@v5
        with:
          build: npm run build
          start: npm run start
          record: true
          browser: chrome
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          DATABASE_URL: postgres://default:uVkMg0qU6dmn@ep-royal-flower-94308348.us-east-1.postgres.vercel-storage.com:5432/verceldb
          GOOGLE_ID: 883604626685-ms65hqna3c0h4c6nh6nfap3ik2f9idsn.apps.googleusercontent.com"
          GOOGLE_SECRET: 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"

          NEXTAUTH_SECRET: YegyDIZNJPqxOkGS4K0F/o9l3SjCxCUR4Q/45rGyOtA
          NEXTAUTH_URL: http://rangachat.com/"
